services:
  db:
    container_name: postgres
    image: postgres:latest    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
       - C:\Users\marve\PDT-postgres:/var/lib/postgresql/data
       - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
